version: '3.8'

services:
  nestapp:
    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env.development
    ports:
      - 3001:3000
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres
    env_file:
      - .env.development
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env.development
    ports:
      - 5050:80
    depends_on:
      - postgresdb
    
volumes:
  pgdata:
